// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binary pixel chunk for efficient data transfer
 * Contains raw RGB data with metadata for direct canvas rendering
 */
export type BinaryPixelChunk = { 
/**
 * Raw RGB pixel data: [r,g,b,r,g,b,...] for each pixel
 */
pixels: Array<number>, 
/**
 * Width of the pixel chunk
 */
width: number, 
/**
 * Height of the pixel chunk  
 */
height: number, 
/**
 * X offset within the full plot
 */
offset_x: number, 
/**
 * Y offset within the full plot
 */
offset_y: number, 
/**
 * Full plot width for coordinate context
 */
total_width: number, 
/**
 * Full plot height for coordinate context
 */
total_height: number, };
