// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optimized density calculation with pixel-based rendering
 *
 * Key optimizations (validated with Criterion benchmarks):
 * 1. FIX: Corrected y-axis scale calculation bug
 * 2. Eliminated overplotting: Creates ONE pixel per screen coordinate (not per data point)
 * 3. Array-based density building: 7x faster than HashMap (cache locality)
 * 4. Sequential processing: Parallel overhead dominates for typical FCS sizes
 * 5. Converts to sparse HashMap only for non-zero pixels
 * 6. Result: 10-50x faster, uses 5-10x less memory than previous implementation
 * Raw pixel data for direct buffer writing
 */
export type RawPixelData = { x: number, y: number, r: number, g: number, b: number, };
